# This file may be used to create an environment using:
# $ conda env create -f <this file>
name: environment
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2024.7.4=hbcca054_0
  - cudatoolkit=11.2.2=hbe64b41_10
  - cudnn=8.1.0.77=h90431f1_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.14=h5eee18b_0
  - pip=24.0=py39h06a4308_0
  - python=3.9.19=h955ad1f_1
  - readline=8.2=h5eee18b_0
  - setuptools=69.5.1=py39h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.43.0=py39h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - cachetools==5.4.0
      - certifi==2024.7.4
      - charset-normalizer==3.3.2
      - contourpy==1.2.1
      - cycler==0.12.1
      - et-xmlfile==1.1.0
      - flatbuffers==24.3.25
      - fonttools==4.53.1
      - gast==0.4.0
      - google-auth==2.32.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.65.1
      - h5py==3.11.0
      - idna==3.7
      - imageio==2.34.2
      - importlib-metadata==8.1.0
      - importlib-resources==6.4.0
      - joblib==1.4.2
      - keras==2.10.0
      - keras-preprocessing==1.1.2
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - libclang==18.1.1
      - markdown==3.6
      - markupsafe==2.1.5
      - matplotlib==3.9.1
      - networkx==3.2.1
      - nibabel==5.2.1
      - numpy==1.26.1
      - oauthlib==3.2.2
      - opencv-python==4.10.0.84
      - openpyxl==3.1.5
      - opt-einsum==3.3.0
      - packaging==24.1
      - pandas==2.2.2
      - pillow==10.4.0
      - protobuf==3.19.6
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - scikit-image==0.24.0
      - scikit-learn==1.5.1
      - scipy==1.13.1
      - six==1.16.0
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.10.0
      - tensorflow-estimator==2.10.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==2.4.0
      - threadpoolctl==3.5.0
      - tifffile==2024.7.24
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - urllib3==2.2.2
      - werkzeug==3.0.3
      - wrapt==1.16.0
      - zipp==3.19.2
prefix: /home/miniconda3/envs/environment
